### ISSUE TITLE
 start an asynchronous event loop while one is already running

### ISSUE THREAD

**Issue by NeonBubbles** [sockysec/Telerecon#11]
I Picked the number 3 and collected user messages from a target channel; 
After the task was finished, I returned to the launcher menu.
If I picked the number 3 again, the error would occur.

Pick a number: 3
Loading userscraper.py...
Traceback (most recent call last):
  File "D:\Telerecon\launcher.py", line 127, in <module>
    exec(open(choice).read())
  File "<string>", line 157, in <module>
  File "D:\anaconda3\lib\asyncio\runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "D:\anaconda3\lib\asyncio\base_events.py", line 649, in run_until_complete
    return future.result()
  File "<string>", line 153, in main
  File "<string>", line 127, in <module>
  File "<string>", line 157, in <module>
  File "D:\anaconda3\lib\asyncio\runners.py", line 33, in run
    raise RuntimeError(
RuntimeError: asyncio.run() cannot be called from a running event loop
sys:1: RuntimeWarning: coroutine 'main' was never awaited

The GPT4 told me:
"The error message RuntimeError: asyncio.run() cannot be called from a running event loop indicates that you are trying to start an asynchronous event loop while one is already running. This can happen when using asyncio.run() in an environment where an event loop is already in place, or when calling asyncio.run() multiple times within the same context."

**Comment by NeonBubbles** [comment]
I realize this is a known issue, But I hope it can be fixed one day.

**Comment by NeonBubbles** [comment]
#12

**Comment by sockysec** [comment]
Thanks @NeonBubbles for the fix

**Comment by NeonBubbles** [comment]
> Thanks @NeonBubbles for the fix

I eventually revoked the changes to launcher.py in the pull request, I'm not sure if this subprocess method is reliable.
However, it indeed could serve as a temporary solution. I plan to address this issue in a new pull request.
