### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by radiophonic** [sockysec/Telerecon#17]
First of all, thanks for the scripts. They work well for the most part, quite a few throwing errors which make them unusable but I'll file those bugs another time.

Secondly, would it be possible to utilize the channel scrape (item 5) on channels that don't have names in a future release? (ie. those that start with a + with a string of characters after.) I am able to do a channel export on these groups through the Telegram program itself, but not from within this particular piece of software.

Thanks again!

**Comment by sockysec** [comment]
Hey, thanks for the positive feedback and I'm glad you are getting some use out of it. 

Out of curiosity, in the example you are talking about, is the target channel publically accessible? Or if it's private, do you have the relevant access (i.e. are you a member)? Channel URLs that start with a +XXXXXXXX are typically private/closed channels/groups. The API access method utilized in this script utilizes the permissions of the associated Telegram account, so it won't be able to access a closed Telegram chat if you don't have access to it. However, i'll add the issue you describe to my list for further investigation and see what I can do.

Do log any errors or ideas if you get a chance, I plan to return to developing this script with updates next month.

**Comment by sockysec** [comment]
Thanks for the extra details, this helps narrow things down! I have encountered similar channels before and will look into what can be done surrounding collection in these situations.
