### ISSUE TITLE
API

### ISSUE THREAD

**Issue by profesionalleet1337** [sockysec/Telerecon#2]
Could i run the tool with some "Api"  which is not in my account . I Mean if I don't have telegram, how i could use it ? Or if I have telegram, but don't want to use my "personal" info for example ? Could i Find api from internet, or some other place, and test the tool ?

**Comment by sockysec** [comment]
Unfortunately, Telerecon requires a valid Telegram account with API access to function. It is unlikely you will be able to find someone else's API details/account with which to run the script.

Suggestions
- If possible, procure a cheap 'burner' SIM card with which to set up a Telegram account and get API access. 
- Alternatively, you may be able to borrow API/account details from a friend or colleague. 
- Utilise your own account. While the not prefered, Telerecon is ve

**Comment by profesionalleet1337** [comment]
> Unfortunately, Telerecon requires a valid Telegram account with API access to function. It is unlikely you will be able to find someone else's API details/account with which to run the script.
> 
> Suggestions
> 
> * If possible, procure a cheap 'burner' SIM card with which to set up a Telegram account and get API access for testing.
> * Alternatively, you may be able to borrow API/account details from a friend or colleague.
> * Utilise your own Telegram account. While not the preferred method, Telerecon is low risk and highly unlikely to result in any form of attribution (I.e. it doesn't actually join any channels etc). However, Telegram itself will be able to associate the API activity with your personal account if this matters to your use case/risk tolerance.
> 
> Hope this helps!

I understand you. Thanks for the quick and detailed reply ! I see that your profile is mainly focused on the OSINT section , which I like , I also follow this "niche" with interest . Do you have some form of contact, like discord/ telegram, or some community where we can exchange ideas/ communicate, and share new things ?

**Comment by sockysec** [comment]
Not to worry, happy to help and glad that you like the look of the project. I don't have a community persae, but you can reach me at SockySec@protonmail.com if you want.
