### ISSUE TITLE
we can't find the "telethon" package

### ISSUE THREAD

**Issue by xijinmu** [sockysec/Telerecon#4]
Current channels:

  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/msys2/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/cloud/conda-forge/noarch
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/osx-64
  - https://mirrors.tuna.tsinghua.edu.cn/anaconda/pkgs/free/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

**Comment by sockysec** [comment]
Hi,

You can find additional information about the telethon package at the following.

- https://pypi.org/project/Telethon/
- https://docs.telethon.dev/en/stable/

To install the telethon package, type the following in terminal.

```
pip install telethon
```

If you are having device/OS specific issues, I suggest trying the Tracelabs pre-build Linux OSINT VM https://www.tracelabs.org/initiatives/osint-vm
